create table public.contatto_annuncio (
  id bigint generated by default as identity primary key,
  uuid_annuncio uuid not null references public.annuncio(uuid) on delete cascade,
  tipo text not null,
  valore text not null,
  constraint contatto_annuncio_tipo_check check (tipo in ('email', 'telefono')),
  constraint contatto_annuncio_valore_check check (char_length(btrim(valore)) between 1 and 254),
  constraint contatto_annuncio_annuncio_tipo_key unique (uuid_annuncio, tipo)
);

alter table public.contatto_annuncio enable row level security;
alter table public.contatto_annuncio force row level security;

revoke all on table public.contatto_annuncio from public, anon, authenticated;
grant select on table public.contatto_annuncio to authenticated;
grant select on table public.contatto_annuncio to service_role;

create policy contatto_annuncio_select_owned
  on public.contatto_annuncio
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.annuncio as owned_announcement
      join public.utente as announcement_owner
        on announcement_owner.utente_uuid = owned_announcement.creato_da
      where owned_announcement.uuid = contatto_annuncio.uuid_annuncio
        and announcement_owner.auth_user_uuid = (select auth.uid())
    )
  );

alter table public.annuncio_torneo_evento
  add column if not exists tipologie_sport text[];

create table private.announcement_submission (
  submission_id uuid primary key,
  announcement_id uuid unique references public.annuncio(uuid) on delete set null,
  utente_id uuid not null references public.utente(utente_uuid) on delete cascade,
  normalized_email text not null,
  anonymous_at_publish boolean not null,
  terms_version text not null,
  privacy_version text not null,
  data_confirmed_at timestamptz not null default now(),
  terms_accepted_at timestamptz not null default now(),
  privacy_accepted_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint announcement_submission_normalized_email_check check (
    normalized_email = lower(btrim(normalized_email))
    and char_length(normalized_email) between 3 and 254
  ),
  constraint announcement_submission_terms_version_check check (
    char_length(btrim(terms_version)) between 1 and 100
  ),
  constraint announcement_submission_privacy_version_check check (
    char_length(btrim(privacy_version)) between 1 and 100
  )
);

create index announcement_submission_anonymous_email_created_idx
  on private.announcement_submission (normalized_email, created_at desc)
  where anonymous_at_publish;
create index announcement_submission_utente_created_idx
  on private.announcement_submission (utente_id, created_at desc);

alter table private.announcement_submission enable row level security;
alter table private.announcement_submission force row level security;

revoke all on table private.announcement_submission from public, anon, authenticated;
grant select on table private.announcement_submission to service_role;
grant usage on schema private to service_role;

create or replace function private.publish_object_has_only_keys(
  p_value jsonb,
  p_allowed_keys text[],
  p_required_keys text[] default array[]::text[]
)
returns boolean
language sql
immutable
parallel safe
security invoker
set search_path = ''
as $$
  select case
    when p_value is null or pg_catalog.jsonb_typeof(p_value) <> 'object' then false
    else
      p_value ?& p_required_keys
      and not exists (
        select 1
        from pg_catalog.jsonb_object_keys(p_value) as object_key(name)
        where not (object_key.name = any (p_allowed_keys))
      )
  end;
$$;

revoke all on function private.publish_object_has_only_keys(jsonb, text[], text[])
  from public, anon, authenticated, service_role;

create or replace function private.publish_text_array_is_valid(
  p_value jsonb,
  p_required boolean default false,
  p_max_items integer default 32,
  p_max_length integer default 120
)
returns boolean
language sql
immutable
parallel safe
security invoker
set search_path = ''
as $$
  select case
    when p_value is null then not p_required
    when pg_catalog.jsonb_typeof(p_value) <> 'array' then false
    else
      pg_catalog.jsonb_array_length(p_value) <= p_max_items
      and (not p_required or pg_catalog.jsonb_array_length(p_value) > 0)
      and not exists (
        select 1
        from pg_catalog.jsonb_array_elements(p_value) as item(value)
        where pg_catalog.jsonb_typeof(item.value) <> 'string'
          or pg_catalog.char_length(pg_catalog.btrim(item.value #>> '{}')) not between 1 and p_max_length
      )
      and (
        select pg_catalog.count(*) = pg_catalog.count(distinct pg_catalog.btrim(item.value #>> '{}'))
        from pg_catalog.jsonb_array_elements(p_value) as item(value)
      )
  end;
$$;

revoke all on function private.publish_text_array_is_valid(jsonb, boolean, integer, integer)
  from public, anon, authenticated, service_role;

create or replace function private.publish_locations_are_valid(p_value jsonb)
returns boolean
language sql
immutable
parallel safe
security invoker
set search_path = ''
as $$
  select case
    when p_value is null or pg_catalog.jsonb_typeof(p_value) <> 'array' then false
    when pg_catalog.jsonb_array_length(p_value) not between 1 and 100 then false
    else
      not exists (
        select 1
        from pg_catalog.jsonb_array_elements(p_value) as location(value)
        where not private.publish_object_has_only_keys(
          location.value,
          array['regione', 'citta'],
          array['regione']
        )
          or pg_catalog.jsonb_typeof(location.value -> 'regione') <> 'string'
          or (
            location.value ? 'citta'
            and pg_catalog.jsonb_typeof(location.value -> 'citta') not in ('string', 'null')
          )
          or nullif(pg_catalog.btrim(location.value ->> 'regione'), '') is null
          or pg_catalog.char_length(pg_catalog.btrim(location.value ->> 'regione')) > 80
          or pg_catalog.char_length(pg_catalog.btrim(coalesce(location.value ->> 'citta', ''))) > 120
      )
      and (
        select pg_catalog.count(*) = pg_catalog.count(
          distinct pg_catalog.jsonb_build_array(
            pg_catalog.btrim(location.value ->> 'regione'),
            nullif(pg_catalog.btrim(location.value ->> 'citta'), '')
          )
        )
        from pg_catalog.jsonb_array_elements(p_value) as location(value)
      )
  end;
$$;

revoke all on function private.publish_locations_are_valid(jsonb)
  from public, anon, authenticated, service_role;

create or replace function private.publish_text_is_valid(
  p_value text,
  p_required boolean default false,
  p_max_length integer default 5000
)
returns boolean
language sql
immutable
parallel safe
security invoker
set search_path = ''
as $$
  select case
    when nullif(pg_catalog.btrim(p_value), '') is null then not p_required
    else pg_catalog.char_length(pg_catalog.btrim(p_value)) <= p_max_length
  end;
$$;

revoke all on function private.publish_text_is_valid(text, boolean, integer)
  from public, anon, authenticated, service_role;

create or replace function private.publish_prizes_are_valid(p_value jsonb)
returns boolean
language sql
immutable
parallel safe
security invoker
set search_path = ''
as $$
  select case
    when p_value is null or pg_catalog.jsonb_typeof(p_value) <> 'array' then false
    when pg_catalog.jsonb_array_length(p_value) > 20 then false
    else not exists (
      select 1
      from pg_catalog.jsonb_array_elements(p_value) as prize(value)
      where not private.publish_object_has_only_keys(
        prize.value,
        array['id', 'posto', 'titoloPremio'],
        array['titoloPremio']
      )
        or not private.publish_text_is_valid(prize.value ->> 'id', false, 100)
        or not private.publish_text_is_valid(prize.value ->> 'posto', false, 160)
        or not private.publish_text_is_valid(prize.value ->> 'titoloPremio', true, 160)
    )
  end;
$$;

revoke all on function private.publish_prizes_are_valid(jsonb)
  from public, anon, authenticated, service_role;

create or replace function private.create_anonymous_publish_profile(
  p_profile_type text,
  p_draft jsonb,
  p_locations jsonb
)
returns uuid
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_profile_id uuid;
  v_subprofile_id bigint;
begin
  if p_draft is null
    or p_locations is null
    or p_profile_type is null
    or p_profile_type not in (
    'giocatore',
    'squadra',
    'staff-sportivo',
    'arbitro',
    'torneo-evento',
    'campi-impianti-sportivi'
  )
    or pg_catalog.jsonb_typeof(p_draft) <> 'object'
    or not private.publish_locations_are_valid(p_locations)
    or pg_catalog.pg_column_size(p_draft) > 128000 then
    raise exception using errcode = '22023', message = 'INVALID_PUBLISH_PAYLOAD';
  end if;

  if (
    case p_profile_type
    when 'giocatore' then
      not private.publish_text_is_valid(p_draft ->> 'nome', true, 160)
      or not private.publish_text_array_is_valid(p_draft -> 'tipologie_sport', true)
      or pg_catalog.jsonb_typeof(p_draft -> 'ruoli_sport') <> 'object'
      or not private.publish_text_array_is_valid(p_draft -> 'ruoli_sport' -> 'principali', true)
    when 'squadra' then
      not private.publish_text_is_valid(p_draft ->> 'nome_societa', true, 160)
      or not private.publish_text_array_is_valid(p_draft -> 'tipologie_sport', true)
    when 'staff-sportivo' then
      not private.publish_text_is_valid(p_draft ->> 'nome', true, 160)
      or not private.publish_text_array_is_valid(p_draft -> 'figure_professionali', true)
    when 'arbitro' then
      not private.publish_text_is_valid(p_draft ->> 'nome', true, 160)
    when 'torneo-evento' then
      not private.publish_text_is_valid(p_draft ->> 'nome_organizzazione', true, 160)
      or not private.publish_text_array_is_valid(p_draft -> 'tipologie_sport', true)
    when 'campi-impianti-sportivi' then
      not private.publish_text_is_valid(p_draft ->> 'nome_organizzazione', true, 160)
      or not private.publish_text_is_valid(p_draft ->> 'sede_principale', true, 160)
      or not private.publish_text_array_is_valid(p_draft -> 'tipologie_sport', true)
      or (
        nullif(pg_catalog.btrim(p_draft ->> 'costo_partenza'), '') is not null
        and pg_catalog.btrim(p_draft ->> 'costo_partenza') !~ '^[0-9]{1,8}([.][0-9]{1,2})?$'
      )
      else true
    end
  ) then
    raise exception using errcode = '22023', message = 'INVALID_PUBLISH_PAYLOAD';
  end if;

  insert into public.profilo (
    uuid_utente,
    creato_il,
    creato_da,
    ultima_modifica_il,
    ultima_modifica_da,
    nascosto,
    tipologia_principale
  ) values (
    null,
    now(),
    null,
    now(),
    null,
    false,
    p_profile_type
  )
  returning uuid into v_profile_id;

  case p_profile_type
    when 'giocatore' then
      insert into public.profilo_giocatore (
        uuid_profilo, sport_principale, nome, cognome, anno_nascita,
        mese_nascita, giorno_nascita, disponibilita, presentazione,
        tipologie_sport, ruoli_sport, piede_principale, altezza, peso,
        storico_carriera, nascosto
      ) values (
        v_profile_id,
        p_draft ->> 'sport_principale',
        p_draft ->> 'nome',
        p_draft ->> 'cognome',
        p_draft ->> 'anno_nascita',
        p_draft ->> 'mese_nascita',
        p_draft ->> 'giorno_nascita',
        p_draft ->> 'disponibilita',
        p_draft ->> 'presentazione',
        array(select jsonb_array_elements_text(coalesce(p_draft -> 'tipologie_sport', '[]'::jsonb))),
        p_draft -> 'ruoli_sport',
        p_draft ->> 'piede_principale',
        p_draft ->> 'altezza',
        p_draft ->> 'peso',
        p_draft -> 'storico_carriera',
        false
      ) returning id into v_subprofile_id;

    when 'squadra' then
      insert into public.profilo_squadra (
        uuid_profilo, sport_principale, nome_societa, tipologie_sport,
        sede_principale, presentazione, nascosto
      ) values (
        v_profile_id,
        p_draft ->> 'sport_principale',
        p_draft ->> 'nome_societa',
        array(select jsonb_array_elements_text(coalesce(p_draft -> 'tipologie_sport', '[]'::jsonb))),
        p_draft ->> 'sede_principale',
        p_draft ->> 'presentazione',
        false
      ) returning id into v_subprofile_id;

    when 'staff-sportivo' then
      insert into public.profilo_staff_sportivo (
        uuid_profilo, sport_principale, nome, cognome, anno_nascita,
        mese_nascita, giorno_nascita, disponibilita, presentazione,
        figure_professionali, storico_esperienze, nascosto
      ) values (
        v_profile_id,
        p_draft ->> 'sport_principale',
        p_draft ->> 'nome',
        p_draft ->> 'cognome',
        p_draft ->> 'anno_nascita',
        p_draft ->> 'mese_nascita',
        p_draft ->> 'giorno_nascita',
        p_draft ->> 'disponibilita',
        p_draft ->> 'presentazione',
        array(select jsonb_array_elements_text(coalesce(p_draft -> 'figure_professionali', '[]'::jsonb))),
        p_draft -> 'storico_esperienze',
        false
      ) returning id into v_subprofile_id;

    when 'arbitro' then
      insert into public.profilo_arbitro (
        uuid_profilo, sport_principale, nome, cognome, anno_nascita,
        mese_nascita, giorno_nascita, disponibilita, presentazione,
        storico_esperienze, nascosto
      ) values (
        v_profile_id,
        p_draft ->> 'sport_principale',
        p_draft ->> 'nome',
        p_draft ->> 'cognome',
        p_draft ->> 'anno_nascita',
        p_draft ->> 'mese_nascita',
        p_draft ->> 'giorno_nascita',
        p_draft ->> 'disponibilita',
        p_draft ->> 'presentazione',
        p_draft -> 'storico_esperienze',
        false
      ) returning id into v_subprofile_id;

    when 'torneo-evento' then
      insert into public.profilo_torneo_evento (
        uuid_profilo, sport_principale, nome_organizzazione,
        tipologie_sport, sede_principale, presentazione, nascosto
      ) values (
        v_profile_id,
        p_draft ->> 'sport_principale',
        p_draft ->> 'nome_organizzazione',
        array(select jsonb_array_elements_text(coalesce(p_draft -> 'tipologie_sport', '[]'::jsonb))),
        p_draft ->> 'sede_principale',
        p_draft ->> 'presentazione',
        false
      ) returning id into v_subprofile_id;

    when 'campi-impianti-sportivi' then
      insert into public.profilo_campi_impianti (
        uuid_profilo, sport_principale, nome_organizzazione,
        tipologie_sport, sede_principale, presentazione, orari,
        costo_partenza, servizi_inclusi, info_aggiuntive, nascosto
      ) values (
        v_profile_id,
        p_draft ->> 'sport_principale',
        p_draft ->> 'nome_organizzazione',
        array(select jsonb_array_elements_text(coalesce(p_draft -> 'tipologie_sport', '[]'::jsonb))),
        p_draft ->> 'sede_principale',
        p_draft ->> 'presentazione',
        p_draft -> 'orari',
        nullif(pg_catalog.btrim(p_draft ->> 'costo_partenza'), '')::numeric(10, 2),
        p_draft ->> 'servizi_inclusi',
        p_draft ->> 'info_aggiuntive',
        false
      ) returning id into v_subprofile_id;
  end case;

  insert into public.localita_profilo (
    uuid_profilo,
    sottoprofilo,
    id_sottoprofilo,
    regione,
    citta
  )
  select
    v_profile_id,
    p_profile_type,
    v_subprofile_id,
    pg_catalog.btrim(location.value ->> 'regione'),
    nullif(pg_catalog.btrim(location.value ->> 'citta'), '')
  from pg_catalog.jsonb_array_elements(p_locations) as location(value);

  return v_profile_id;
end;
$$;

revoke all on function private.create_anonymous_publish_profile(text, jsonb, jsonb)
  from public, anon, authenticated, service_role;

create or replace function public.publish_announcement_v1(
  p_submission_id uuid,
  p_payload jsonb,
  p_terms_version text,
  p_privacy_version text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_existing private.announcement_submission%rowtype;
  v_existing_auth_user_id uuid;
  v_auth_user_id uuid;
  v_utente_id uuid;
  v_utente_auth_user_id uuid;
  v_utente_email text;
  v_registered_at timestamptz;
  v_is_anonymous boolean;
  v_db_email text;
  v_jwt_email text;
  v_normalized_email text;
  v_contact_email text;
  v_contact_phone text;
  v_email_confirmed_at timestamptz;
  v_profile_id uuid;
  v_profile_type text;
  v_announcement_type text;
  v_announcement_id uuid;
  v_last_anonymous_publish timestamptz;
  v_now timestamptz := pg_catalog.statement_timestamp();
  v_detail jsonb;
  v_profile_sports text[];
  v_profile_roles jsonb;
  v_profile_figures text[];
  v_profile_experiences jsonb;
  v_profile_availability text;
begin
  if p_submission_id is null
    or p_payload is null
    or pg_catalog.jsonb_typeof(p_payload) <> 'object'
    or pg_catalog.pg_column_size(p_payload) > 256000
    or not private.publish_object_has_only_keys(
      p_payload,
      array[
        'profile_type',
        'announcement_type',
        'profile_draft',
        'profile_locations',
        'detail',
        'announcement_locations',
        'contacts'
      ],
      array[
        'profile_type',
        'announcement_type',
        'profile_draft',
        'profile_locations',
        'detail',
        'announcement_locations',
        'contacts'
      ]
    )
    -- These values are consent-receipt evidence, so callers cannot choose
    -- arbitrary versions by invoking the authenticated RPC directly.
    or p_terms_version is distinct from '2026-08-24'
    or p_privacy_version is distinct from '2026-08-24' then
    raise exception using errcode = '22023', message = 'INVALID_PUBLISH_PAYLOAD';
  end if;

  v_profile_type := p_payload ->> 'profile_type';
  v_announcement_type := p_payload ->> 'announcement_type';
  v_detail := p_payload -> 'detail';

  if v_profile_type is null
    or v_announcement_type is null
    or v_profile_type not in (
    'giocatore',
    'squadra',
    'staff-sportivo',
    'arbitro',
    'torneo-evento',
    'campi-impianti-sportivi'
  ) then
    raise exception using errcode = '22023', message = 'PROFILE_TYPE_UNAVAILABLE';
  end if;

  if not (
    (v_profile_type = 'giocatore' and v_announcement_type = 'annuncio_giocatore')
    or (v_profile_type = 'squadra' and v_announcement_type in (
      'annuncio_squadra_cerca_giocatore',
      'annuncio_squadra_cerca_staff',
      'annuncio_squadra_cerca_partita',
      'annuncio_squadra_cerca_sponsor'
    ))
    or (v_profile_type = 'staff-sportivo' and v_announcement_type = 'annuncio_staff_sportivo')
    or (v_profile_type = 'arbitro' and v_announcement_type = 'annuncio_arbitro')
    or (v_profile_type = 'torneo-evento' and v_announcement_type = 'annuncio_torneo_evento')
    or (v_profile_type = 'campi-impianti-sportivi' and v_announcement_type = 'annuncio_campo_impianto')
  ) or v_detail is null
    or pg_catalog.jsonb_typeof(v_detail) <> 'object'
    or pg_catalog.pg_column_size(v_detail) > 128000
    or not private.publish_locations_are_valid(p_payload -> 'announcement_locations')
    or not private.publish_object_has_only_keys(
      p_payload -> 'contacts',
      array['email', 'phone'],
      array['email', 'phone']
    )
    or pg_catalog.jsonb_typeof(p_payload -> 'contacts' -> 'email') not in ('string', 'null')
    or pg_catalog.jsonb_typeof(p_payload -> 'contacts' -> 'phone') not in ('string', 'null') then
    raise exception using errcode = '22023', message = 'INVALID_PUBLISH_PAYLOAD';
  end if;

  v_contact_email := nullif(
    pg_catalog.lower(pg_catalog.btrim(p_payload -> 'contacts' ->> 'email')),
    ''
  );
  v_contact_phone := nullif(pg_catalog.btrim(p_payload -> 'contacts' ->> 'phone'), '');

  if (v_contact_email is null and v_contact_phone is null)
    or (
      v_contact_email is not null
      and (
        not private.publish_text_is_valid(v_contact_email, true, 254)
        or v_contact_email !~ '^[^@[:space:]]+@[^@[:space:]]+[.][^@[:space:]]+$'
      )
    )
    or (
      v_contact_phone is not null
      and (
        pg_catalog.char_length(v_contact_phone) > 40
        or v_contact_phone !~ '^[+0-9().[:space:]-]+$'
        or pg_catalog.char_length(pg_catalog.regexp_replace(v_contact_phone, '[^0-9]', '', 'g')) not between 6 and 20
      )
    ) then
    raise exception using errcode = '22023', message = 'INVALID_PUBLISH_PAYLOAD';
  end if;

  if (
    case v_announcement_type
    when 'annuncio_giocatore' then
      not private.publish_text_is_valid(v_detail ->> 'descrizione_aggiuntiva', true, 5000)
    when 'annuncio_squadra_cerca_giocatore' then
      not private.publish_text_array_is_valid(v_detail -> 'ruoli_principali', true)
      or not private.publish_text_array_is_valid(v_detail -> 'ruoli_secondari')
      or not private.publish_text_array_is_valid(v_detail -> 'annate_ricercate')
      or not private.publish_text_is_valid(v_detail ->> 'stagione', false, 80)
      or not private.publish_text_is_valid(v_detail ->> 'descrizione_aggiuntiva', true, 5000)
    when 'annuncio_squadra_cerca_staff' then
      not private.publish_text_is_valid(v_detail ->> 'figura_ricercata', true, 160)
      or not private.publish_text_is_valid(v_detail ->> 'settore', false, 160)
      or not private.publish_text_is_valid(v_detail ->> 'requisiti', true, 5000)
      or not private.publish_text_is_valid(v_detail ->> 'descrizione_aggiuntiva', false, 5000)
      or (
        nullif(pg_catalog.btrim(v_detail ->> 'compenso_mensile'), '') is not null
        and pg_catalog.btrim(v_detail ->> 'compenso_mensile') !~ '^[0-9]{1,8}([.][0-9]{1,2})?$'
      )
      or (
        nullif(pg_catalog.btrim(v_detail ->> 'periodo_dal'), '') is not null
        and pg_catalog.btrim(v_detail ->> 'periodo_dal') !~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
      )
      or (
        nullif(pg_catalog.btrim(v_detail ->> 'periodo_al'), '') is not null
        and pg_catalog.btrim(v_detail ->> 'periodo_al') !~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
      )
      or (
        nullif(pg_catalog.btrim(v_detail ->> 'periodo_dal'), '') is not null
        and nullif(pg_catalog.btrim(v_detail ->> 'periodo_al'), '') is not null
        and (v_detail ->> 'periodo_dal') > (v_detail ->> 'periodo_al')
      )
    when 'annuncio_squadra_cerca_partita' then
      not private.publish_text_array_is_valid(v_detail -> 'categorie_avversario', true)
      or not private.publish_text_is_valid(v_detail ->> 'disponibilita_trasferta', false, 40)
      or not private.publish_text_is_valid(v_detail ->> 'descrizione_aggiuntiva', false, 5000)
      or (
        nullif(pg_catalog.btrim(v_detail ->> 'periodo_dal'), '') is not null
        and pg_catalog.btrim(v_detail ->> 'periodo_dal') !~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
      )
      or (
        nullif(pg_catalog.btrim(v_detail ->> 'periodo_al'), '') is not null
        and pg_catalog.btrim(v_detail ->> 'periodo_al') !~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
      )
      or (
        nullif(pg_catalog.btrim(v_detail ->> 'periodo_dal'), '') is not null
        and nullif(pg_catalog.btrim(v_detail ->> 'periodo_al'), '') is not null
        and (v_detail ->> 'periodo_dal') > (v_detail ->> 'periodo_al')
      )
      or (
        (nullif(pg_catalog.btrim(v_detail ->> 'orario_dalle'), '') is null)
        <> (nullif(pg_catalog.btrim(v_detail ->> 'orario_alle'), '') is null)
      )
      or (
        nullif(pg_catalog.btrim(v_detail ->> 'orario_dalle'), '') is not null
        and pg_catalog.btrim(v_detail ->> 'orario_dalle') !~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'
      )
      or (
        nullif(pg_catalog.btrim(v_detail ->> 'orario_alle'), '') is not null
        and pg_catalog.btrim(v_detail ->> 'orario_alle') !~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'
      )
    when 'annuncio_squadra_cerca_sponsor' then
      not private.publish_text_is_valid(v_detail ->> 'categoria_settore', true, 160)
      or not private.publish_text_is_valid(v_detail ->> 'supporto_cercato', true, 5000)
      or not private.publish_text_is_valid(v_detail ->> 'offerta_fornita', true, 5000)
      or not private.publish_text_is_valid(v_detail ->> 'descrizione_aggiuntiva', false, 5000)
    when 'annuncio_staff_sportivo' then
      not private.publish_text_array_is_valid(v_detail -> 'tipologie_sport', true)
      or not private.publish_text_array_is_valid(v_detail -> 'categorie_ricercate')
      or not private.publish_text_is_valid(v_detail ->> 'disponibilita_spostamento', false, 40)
      or not private.publish_text_is_valid(v_detail ->> 'descrizione_aggiuntiva', true, 5000)
    when 'annuncio_arbitro' then
      not private.publish_text_array_is_valid(v_detail -> 'tipologie_sport', true)
      or not private.publish_text_array_is_valid(v_detail -> 'categorie_ricercate')
      or not private.publish_text_is_valid(v_detail ->> 'automunito', false, 40)
      or not private.publish_text_is_valid(v_detail ->> 'disponibilita_spostamento', false, 40)
      or not private.publish_text_is_valid(v_detail ->> 'descrizione_aggiuntiva', true, 5000)
    when 'annuncio_torneo_evento' then
      not private.publish_text_is_valid(v_detail ->> 'nome_evento', true, 160)
      or not private.publish_text_array_is_valid(v_detail -> 'tipologie_sport', true)
      or not private.publish_text_is_valid(v_detail ->> 'modalita_iscrizione', false, 40)
      or not private.publish_text_is_valid(v_detail ->> 'descrizione_aggiuntiva', true, 5000)
      or coalesce(nullif(pg_catalog.btrim(v_detail ->> 'tipo_partecipazione'), ''), '')
        not in ('giocatore', 'squadra')
      or (
        nullif(pg_catalog.btrim(v_detail ->> 'annate_ammesse_da'), '') is not null
        and pg_catalog.btrim(v_detail ->> 'annate_ammesse_da') !~ '^[0-9]{4}$'
      )
      or (
        nullif(pg_catalog.btrim(v_detail ->> 'annate_ammesse_a'), '') is not null
        and pg_catalog.btrim(v_detail ->> 'annate_ammesse_a') !~ '^[0-9]{4}$'
      )
      or (
        nullif(pg_catalog.btrim(v_detail ->> 'annate_ammesse_da'), '') is not null
        and nullif(pg_catalog.btrim(v_detail ->> 'annate_ammesse_a'), '') is not null
        and (v_detail ->> 'annate_ammesse_da') > (v_detail ->> 'annate_ammesse_a')
      )
      or (
        nullif(pg_catalog.btrim(v_detail ->> 'numero_squadre'), '') is not null
        and pg_catalog.btrim(v_detail ->> 'numero_squadre') !~ '^[1-9][0-9]{0,5}$'
      )
      or (
        nullif(pg_catalog.btrim(v_detail ->> 'costo_partecipazione'), '') is not null
        and pg_catalog.btrim(v_detail ->> 'costo_partecipazione') !~ '^[0-9]{1,8}([.][0-9]{1,2})?$'
      )
      or not private.publish_prizes_are_valid(v_detail -> 'lista_premi_trofei')
    when 'annuncio_campo_impianto' then
      not private.publish_text_array_is_valid(v_detail -> 'tipologie_sport', true)
      or not private.publish_text_is_valid(v_detail ->> 'orari', false, 5000)
      or not private.publish_text_is_valid(v_detail ->> 'servizi_inclusi', false, 5000)
      or not private.publish_text_is_valid(v_detail ->> 'descrizione_aggiuntiva', true, 5000)
      or (
        nullif(pg_catalog.btrim(v_detail ->> 'costo_partenza'), '') is not null
        and pg_catalog.btrim(v_detail ->> 'costo_partenza') !~ '^[0-9]{1,8}([.][0-9]{1,2})?$'
      )
      else true
    end
  ) then
    raise exception using errcode = '22023', message = 'INVALID_PUBLISH_PAYLOAD';
  end if;

  v_auth_user_id := (select auth.uid());
  if v_auth_user_id is null then
    raise exception using errcode = '28000', message = 'AUTH_REQUIRED';
  end if;

  select
    pg_catalog.lower(pg_catalog.btrim(auth_user.email)),
    auth_user.email_confirmed_at
  into v_db_email, v_email_confirmed_at
  from auth.users as auth_user
  where auth_user.id = v_auth_user_id;

  if not found
    or not private.publish_text_is_valid(v_db_email, true, 254)
    or v_email_confirmed_at is null then
    raise exception using errcode = '28000', message = 'EMAIL_VERIFICATION_REQUIRED';
  end if;

  v_normalized_email := v_db_email;
  v_jwt_email := pg_catalog.lower(pg_catalog.btrim((select auth.jwt()) ->> 'email'));
  if v_jwt_email is distinct from v_db_email then
    raise exception using errcode = '28000', message = 'EMAIL_ACCOUNT_MISMATCH';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('publish-submission:' || p_submission_id::text, 0)
  );

  select *
  into v_existing
  from private.announcement_submission
  where submission_id = p_submission_id;

  if found then
    select public_user.auth_user_uuid
    into v_existing_auth_user_id
    from public.utente as public_user
    where public_user.utente_uuid = v_existing.utente_id;

    if v_existing_auth_user_id is distinct from v_auth_user_id then
      raise exception using errcode = '22023', message = 'SUBMISSION_ID_CONFLICT';
    end if;

    -- Keep the submission receipt after an announcement is deleted: it is both
    -- the idempotency key and the source of the anonymous 24-hour limit.
    if v_existing.announcement_id is null then
      raise exception using errcode = '55000', message = 'SUBMISSION_ALREADY_CONSUMED';
    end if;

    return pg_catalog.jsonb_build_object(
      'status', 'success',
      'announcementId', v_existing.announcement_id,
      'idempotent', true
    );
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('utente-email:' || v_normalized_email, 0)
  );

  select
    public_user.utente_uuid,
    public_user.auth_user_uuid,
    public_user.indirizzo_email,
    public_user.registrato_il
  into
    v_utente_id,
    v_utente_auth_user_id,
    v_utente_email,
    v_registered_at
  from public.utente as public_user
  where public_user.auth_user_uuid = v_auth_user_id
  for update;

  if found then
    if pg_catalog.lower(pg_catalog.btrim(v_utente_email)) is distinct from v_normalized_email
      or exists (
        select 1
        from public.utente as duplicate_email_user
        where pg_catalog.lower(pg_catalog.btrim(duplicate_email_user.indirizzo_email)) = v_normalized_email
          and duplicate_email_user.utente_uuid <> v_utente_id
      ) then
      raise exception using errcode = '28000', message = 'EMAIL_ACCOUNT_MISMATCH';
    end if;
  else
    select
      public_user.utente_uuid,
      public_user.auth_user_uuid,
      public_user.indirizzo_email,
      public_user.registrato_il
    into
      v_utente_id,
      v_utente_auth_user_id,
      v_utente_email,
      v_registered_at
    from public.utente as public_user
    where pg_catalog.lower(pg_catalog.btrim(public_user.indirizzo_email)) = v_normalized_email
    for update;

    if found then
      if v_utente_auth_user_id is not null
        and v_utente_auth_user_id is distinct from v_auth_user_id then
        raise exception using errcode = '28000', message = 'EMAIL_ACCOUNT_MISMATCH';
      end if;

      update public.utente
      set
        auth_user_uuid = v_auth_user_id,
        indirizzo_email = v_normalized_email,
        ultima_modifica_il = v_now
      where utente_uuid = v_utente_id
      returning registrato_il into v_registered_at;
    else
      insert into public.utente (
        auth_user_uuid,
        indirizzo_email,
        tipologia_utente,
        creato_il,
        ultima_modifica_il,
        registrato_il
      ) values (
        v_auth_user_id,
        v_normalized_email,
        'Utente',
        v_now,
        v_now,
        null
      )
      returning utente_uuid, registrato_il
      into v_utente_id, v_registered_at;
    end if;
  end if;

  v_is_anonymous := v_registered_at is null;

  if v_is_anonymous then
    select pg_catalog.max(submission.created_at)
    into v_last_anonymous_publish
    from private.announcement_submission as submission
    where submission.anonymous_at_publish
      and submission.normalized_email = v_normalized_email
      and submission.created_at > v_now - interval '24 hours';

    if v_last_anonymous_publish is not null then
      return pg_catalog.jsonb_build_object(
        'status', 'rate_limited',
        'retryAt', v_last_anonymous_publish + interval '24 hours'
      );
    end if;

    v_profile_id := private.create_anonymous_publish_profile(
      v_profile_type,
      p_payload -> 'profile_draft',
      p_payload -> 'profile_locations'
    );
  else
    select uuid
    into v_profile_id
    from public.profilo
    where uuid_utente = v_utente_id
      and nascosto = false
    for share;

    if v_profile_id is null then
      raise exception using errcode = 'P0001', message = 'PROFILE_NOT_ENABLED';
    end if;
  end if;

  case v_profile_type
    when 'giocatore' then
      select tipologie_sport, ruoli_sport
      into v_profile_sports, v_profile_roles
      from public.profilo_giocatore
      where uuid_profilo = v_profile_id and nascosto = false
      for share;
      if not found
        or not private.publish_text_array_is_valid(pg_catalog.to_jsonb(v_profile_sports), true)
        or pg_catalog.jsonb_typeof(v_profile_roles) <> 'object'
        or not private.publish_text_array_is_valid(v_profile_roles -> 'principali', true)
        or not private.publish_text_array_is_valid(v_profile_roles -> 'specifici') then
        raise exception using errcode = 'P0001', message = 'PROFILE_NOT_ENABLED';
      end if;
    when 'squadra' then
      select tipologie_sport
      into v_profile_sports
      from public.profilo_squadra
      where uuid_profilo = v_profile_id and nascosto = false
      for share;
      if not found
        or not private.publish_text_array_is_valid(pg_catalog.to_jsonb(v_profile_sports), true) then
        raise exception using errcode = 'P0001', message = 'PROFILE_NOT_ENABLED';
      end if;
    when 'staff-sportivo' then
      select figure_professionali, storico_esperienze, disponibilita
      into v_profile_figures, v_profile_experiences, v_profile_availability
      from public.profilo_staff_sportivo
      where uuid_profilo = v_profile_id and nascosto = false
      for share;
      if not found
        or not private.publish_text_array_is_valid(pg_catalog.to_jsonb(v_profile_figures), true) then
        raise exception using errcode = 'P0001', message = 'PROFILE_NOT_ENABLED';
      end if;
    when 'arbitro' then
      select storico_esperienze, disponibilita
      into v_profile_experiences, v_profile_availability
      from public.profilo_arbitro
      where uuid_profilo = v_profile_id and nascosto = false
      for share;
      if not found then
        raise exception using errcode = 'P0001', message = 'PROFILE_NOT_ENABLED';
      end if;
    when 'torneo-evento' then
      perform 1
      from public.profilo_torneo_evento
      where uuid_profilo = v_profile_id and nascosto = false
      for share;
      if not found then
        raise exception using errcode = 'P0001', message = 'PROFILE_NOT_ENABLED';
      end if;
    when 'campi-impianti-sportivi' then
      perform 1
      from public.profilo_campi_impianti
      where uuid_profilo = v_profile_id and nascosto = false
      for share;
      if not found then
        raise exception using errcode = 'P0001', message = 'PROFILE_NOT_ENABLED';
      end if;
  end case;

  insert into public.annuncio (
    autore_annuncio,
    creato_da,
    creato_il,
    info_stato_annuncio,
    livello_annuncio,
    nascosto,
    privato,
    stato_annuncio,
    tipologia_annuncio,
    ultima_modifica_da,
    ultima_modifica_il
  ) values (
    v_profile_id,
    v_utente_id,
    v_now,
    'Annuncio ricevuto e in attesa di revisione.',
    'gratuito',
    false,
    false,
    'in_revisione',
    v_announcement_type,
    v_utente_id,
    v_now
  )
  returning uuid into v_announcement_id;

  case v_announcement_type
    when 'annuncio_giocatore' then
      insert into public.annuncio_giocatore (
        uuid_annuncio, tipologie_sport, ruoli_principali, ruoli_secondari,
        descrizione_aggiuntiva
      ) values (
        v_announcement_id,
        coalesce(v_profile_sports, array[]::text[]),
        array(select jsonb_array_elements_text(coalesce(v_profile_roles -> 'principali', '[]'::jsonb))),
        array(select jsonb_array_elements_text(coalesce(v_profile_roles -> 'specifici', '[]'::jsonb))),
        v_detail ->> 'descrizione_aggiuntiva'
      );

    when 'annuncio_squadra_cerca_giocatore' then
      insert into public.annuncio_squadra_cerca_giocatore (
        uuid_annuncio, tipologie_sport, ruoli_principali, ruoli_secondari,
        annate_ricercate, stagione, descrizione_aggiuntiva
      ) values (
        v_announcement_id,
        coalesce(v_profile_sports, array[]::text[]),
        array(select jsonb_array_elements_text(coalesce(v_detail -> 'ruoli_principali', '[]'::jsonb))),
        array(select jsonb_array_elements_text(coalesce(v_detail -> 'ruoli_secondari', '[]'::jsonb))),
        array(select jsonb_array_elements_text(coalesce(v_detail -> 'annate_ricercate', '[]'::jsonb))),
        v_detail ->> 'stagione',
        v_detail ->> 'descrizione_aggiuntiva'
      );

    when 'annuncio_squadra_cerca_staff' then
      insert into public.annuncio_squadra_cerca_staff (
        uuid_annuncio, figura_ricercata, settore, compenso_mensile,
        requisiti, periodo_dal, periodo_al, descrizione_aggiuntiva
      ) values (
        v_announcement_id,
        v_detail ->> 'figura_ricercata',
        v_detail ->> 'settore',
        nullif(pg_catalog.btrim(v_detail ->> 'compenso_mensile'), '')::numeric,
        v_detail ->> 'requisiti',
        nullif(pg_catalog.btrim(v_detail ->> 'periodo_dal'), ''),
        nullif(pg_catalog.btrim(v_detail ->> 'periodo_al'), ''),
        v_detail ->> 'descrizione_aggiuntiva'
      );

    when 'annuncio_squadra_cerca_partita' then
      insert into public.annuncio_squadra_cerca_partita (
        uuid_annuncio, categorie_avversario, periodo_dal, periodo_al,
        orario_dalle, orario_alle, disponibilita_trasferta,
        descrizione_aggiuntiva
      ) values (
        v_announcement_id,
        array(select jsonb_array_elements_text(coalesce(v_detail -> 'categorie_avversario', '[]'::jsonb))),
        nullif(pg_catalog.btrim(v_detail ->> 'periodo_dal'), ''),
        nullif(pg_catalog.btrim(v_detail ->> 'periodo_al'), ''),
        nullif(pg_catalog.btrim(v_detail ->> 'orario_dalle'), ''),
        nullif(pg_catalog.btrim(v_detail ->> 'orario_alle'), ''),
        v_detail ->> 'disponibilita_trasferta',
        v_detail ->> 'descrizione_aggiuntiva'
      );

    when 'annuncio_squadra_cerca_sponsor' then
      insert into public.annuncio_squadra_cerca_sponsor (
        uuid_annuncio, categoria_settore, supporto_cercato,
        offerta_fornita, descrizione_aggiuntiva
      ) values (
        v_announcement_id,
        v_detail ->> 'categoria_settore',
        v_detail ->> 'supporto_cercato',
        v_detail ->> 'offerta_fornita',
        v_detail ->> 'descrizione_aggiuntiva'
      );

    when 'annuncio_staff_sportivo' then
      insert into public.annuncio_staff_sportivo (
        uuid_annuncio, tipologie_sport, figure_professionali,
        categorie_ricercate, descrizione_aggiuntiva, lista_esperienze,
        disponibilita_occupazione, disponibilita_spostamento
      ) values (
        v_announcement_id,
        array(select jsonb_array_elements_text(coalesce(v_detail -> 'tipologie_sport', '[]'::jsonb))),
        coalesce(v_profile_figures, array[]::text[]),
        array(select jsonb_array_elements_text(coalesce(v_detail -> 'categorie_ricercate', '[]'::jsonb))),
        v_detail ->> 'descrizione_aggiuntiva',
        v_profile_experiences,
        v_profile_availability,
        v_detail ->> 'disponibilita_spostamento'
      );

    when 'annuncio_arbitro' then
      insert into public.annuncio_arbitro (
        uuid_annuncio, tipologie_sport, categorie_ricercate,
        descrizione_aggiuntiva, lista_esperienze, disponibilita_occupazione,
        disponibilita_spostamento, automunito
      ) values (
        v_announcement_id,
        array(select jsonb_array_elements_text(coalesce(v_detail -> 'tipologie_sport', '[]'::jsonb))),
        array(select jsonb_array_elements_text(coalesce(v_detail -> 'categorie_ricercate', '[]'::jsonb))),
        v_detail ->> 'descrizione_aggiuntiva',
        v_profile_experiences,
        v_profile_availability,
        v_detail ->> 'disponibilita_spostamento',
        v_detail ->> 'automunito'
      );

    when 'annuncio_torneo_evento' then
      insert into public.annuncio_torneo_evento (
        uuid_annuncio, nome_evento, tipologie_sport, modalita_iscrizione,
        annate_ammesse_da, annate_ammesse_a, numero_squadre,
        costo_partecipazione, tipo_partecipazione, lista_premi_trofei,
        descrizione_aggiuntiva
      ) values (
        v_announcement_id,
        v_detail ->> 'nome_evento',
        array(select jsonb_array_elements_text(coalesce(v_detail -> 'tipologie_sport', '[]'::jsonb))),
        v_detail ->> 'modalita_iscrizione',
        nullif(pg_catalog.btrim(v_detail ->> 'annate_ammesse_da'), ''),
        nullif(pg_catalog.btrim(v_detail ->> 'annate_ammesse_a'), ''),
        nullif(pg_catalog.btrim(v_detail ->> 'numero_squadre'), '')::integer,
        nullif(pg_catalog.btrim(v_detail ->> 'costo_partecipazione'), '')::numeric,
        v_detail ->> 'tipo_partecipazione',
        v_detail -> 'lista_premi_trofei',
        v_detail ->> 'descrizione_aggiuntiva'
      );

    when 'annuncio_campo_impianto' then
      insert into public.annuncio_campo_impianto (
        uuid_annuncio, tipologie_sport, orari, costo_partenza,
        servizi_inclusi, descrizione_aggiuntiva
      ) values (
        v_announcement_id,
        array(select jsonb_array_elements_text(coalesce(v_detail -> 'tipologie_sport', '[]'::jsonb))),
        case
          when nullif(pg_catalog.btrim(v_detail ->> 'orari'), '') is null then null
          else jsonb_build_object('descrizione', v_detail ->> 'orari')
        end,
        nullif(pg_catalog.btrim(v_detail ->> 'costo_partenza'), '')::numeric,
        v_detail ->> 'servizi_inclusi',
        v_detail ->> 'descrizione_aggiuntiva'
      );
  end case;

  insert into public.localita_annuncio (uuid_annuncio, regione, citta)
  select
    v_announcement_id,
    pg_catalog.btrim(location.value ->> 'regione'),
    nullif(pg_catalog.btrim(location.value ->> 'citta'), '')
  from pg_catalog.jsonb_array_elements(p_payload -> 'announcement_locations') as location(value);

  if v_contact_email is not null then
    insert into public.contatto_annuncio (uuid_annuncio, tipo, valore)
    values (v_announcement_id, 'email', v_contact_email);
  end if;

  if v_contact_phone is not null then
    insert into public.contatto_annuncio (uuid_annuncio, tipo, valore)
    values (v_announcement_id, 'telefono', v_contact_phone);
  end if;

  insert into private.announcement_submission (
    submission_id,
    announcement_id,
    utente_id,
    normalized_email,
    anonymous_at_publish,
    terms_version,
    privacy_version,
    data_confirmed_at,
    terms_accepted_at,
    privacy_accepted_at,
    created_at
  ) values (
    p_submission_id,
    v_announcement_id,
    v_utente_id,
    v_normalized_email,
    v_is_anonymous,
    pg_catalog.btrim(p_terms_version),
    pg_catalog.btrim(p_privacy_version),
    v_now,
    v_now,
    v_now,
    v_now
  );

  return pg_catalog.jsonb_build_object(
    'status', 'success',
    'announcementId', v_announcement_id,
    'idempotent', false
  );
end;
$$;

revoke all on function public.publish_announcement_v1(uuid, jsonb, text, text)
  from public, anon, authenticated, service_role;
grant execute on function public.publish_announcement_v1(uuid, jsonb, text, text)
  to authenticated;
