-- Add one public highlights link to player profiles and enforce the minimum
-- profile age at the database boundary.

create table if not exists public.media_profilo (
  id bigint generated by default as identity primary key,
  uuid_profilo uuid not null,
  formato_media text,
  link_media text not null
);

alter table public.media_profilo
  alter column uuid_profilo set not null,
  alter column link_media set not null;

alter table public.media_profilo
  drop constraint if exists media_profilo_uuid_profilo_fkey;

alter table public.media_profilo
  add constraint media_profilo_uuid_profilo_fkey
  foreign key (uuid_profilo)
  references public.profilo (uuid)
  on delete cascade;

comment on table public.media_profilo is
  'Tabella relazione per collegare file e link multimediali a un profilo';

create index if not exists media_profilo_uuid_profilo_idx
  on public.media_profilo (uuid_profilo);

delete from public.media_profilo as older
using public.media_profilo as newer
where older.uuid_profilo = newer.uuid_profilo
  and older.formato_media = 'video_highlights'
  and newer.formato_media = 'video_highlights'
  and older.id < newer.id;

create unique index if not exists media_profilo_video_highlights_uidx
  on public.media_profilo (uuid_profilo)
  where formato_media = 'video_highlights';

alter table public.media_profilo enable row level security;

revoke all on table public.media_profilo from public, anon, authenticated;
grant select on table public.media_profilo to authenticated;
grant all on table public.media_profilo to service_role;

do $$
declare
  v_sequence text := pg_catalog.pg_get_serial_sequence('public.media_profilo', 'id');
begin
  if v_sequence is not null then
    execute pg_catalog.format(
      'grant usage, select on sequence %s to service_role',
      v_sequence
    );
  end if;
end;
$$;

drop policy if exists media_profilo_select_own on public.media_profilo;
create policy media_profilo_select_own
  on public.media_profilo
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.profilo as owned_profile
      join public.utente as owned_user
        on owned_user.utente_uuid = owned_profile.uuid_utente
      where owned_profile.uuid = media_profilo.uuid_profilo
        and owned_user.auth_user_uuid = (select auth.uid())
    )
  );

create or replace function private.save_player_highlights_for_profile_v1(
  p_profile_id uuid,
  p_profile_type text,
  p_draft jsonb
)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_link text;
begin
  if p_profile_type <> 'giocatore' then
    return;
  end if;

  if p_profile_id is null
    or p_draft is null
    or pg_catalog.jsonb_typeof(p_draft) <> 'object' then
    raise exception using errcode = '22023', message = 'INVALID_PROFILE_PAYLOAD';
  end if;

  if not p_draft ? 'video_highlights' then
    return;
  end if;

  if not exists (
    select 1
    from public.profilo_giocatore
    where uuid_profilo = p_profile_id
  ) then
    raise exception using errcode = 'P0001', message = 'PROFILE_NOT_FOUND';
  end if;

  v_link := nullif(pg_catalog.btrim(p_draft ->> 'video_highlights'), '');
  if v_link is not null and (
    pg_catalog.char_length(v_link) > 2048
    or v_link !~* '^https?://[^[:space:]]+$'
  ) then
    raise exception using errcode = '22023', message = 'INVALID_PROFILE_VIDEO_LINK';
  end if;

  if v_link is null then
    delete from public.media_profilo
    where uuid_profilo = p_profile_id
      and formato_media = 'video_highlights';
    return;
  end if;

  insert into public.media_profilo (
    uuid_profilo,
    formato_media,
    link_media
  ) values (
    p_profile_id,
    'video_highlights',
    v_link
  )
  on conflict (uuid_profilo)
    where formato_media = 'video_highlights'
  do update set link_media = excluded.link_media;
end;
$$;

revoke all on function private.save_player_highlights_for_profile_v1(uuid, text, jsonb)
  from public, anon, authenticated, service_role;
grant execute on function private.save_player_highlights_for_profile_v1(uuid, text, jsonb)
  to service_role;

-- Every existing registered profile flow already calls this private writer.
-- Keep its signature stable and add media synchronization around the old body.
alter function private.save_owned_subprofile_internal_v1(uuid, text, jsonb, jsonb)
  rename to save_owned_subprofile_core_v1;

revoke all on function private.save_owned_subprofile_core_v1(uuid, text, jsonb, jsonb)
  from public, anon, authenticated, service_role;
grant execute on function private.save_owned_subprofile_core_v1(uuid, text, jsonb, jsonb)
  to service_role;

create or replace function private.save_owned_subprofile_internal_v1(
  p_internal_user_id uuid,
  p_profile_type text,
  p_draft jsonb,
  p_locations jsonb
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_profile_id uuid;
  v_result jsonb;
begin
  v_result := private.save_owned_subprofile_core_v1(
    p_internal_user_id,
    p_profile_type,
    p_draft,
    p_locations
  );

  if p_profile_type = 'giocatore' then
    select uuid
    into v_profile_id
    from public.profilo
    where uuid_utente = p_internal_user_id;

    perform private.save_player_highlights_for_profile_v1(
      v_profile_id,
      p_profile_type,
      p_draft
    );
  end if;

  return v_result;
end;
$$;

revoke all on function private.save_owned_subprofile_internal_v1(uuid, text, jsonb, jsonb)
  from public, anon, authenticated, service_role;
grant execute on function private.save_owned_subprofile_internal_v1(uuid, text, jsonb, jsonb)
  to service_role;

-- The anonymous publish path creates its profile inside the publishing core.
-- Wrap the current v2 endpoint so the new profile receives its highlights link
-- without changing the public RPC signature.
alter function public.publish_announcement_v2(uuid, jsonb, text, text, text)
  set schema private;
alter function private.publish_announcement_v2(uuid, jsonb, text, text, text)
  rename to publish_announcement_core_v2;

revoke all on function private.publish_announcement_core_v2(uuid, jsonb, text, text, text)
  from public, anon, authenticated, service_role;

create or replace function public.publish_announcement_v2(
  p_submission_id uuid,
  p_payload jsonb,
  p_terms_version text,
  p_privacy_version text,
  p_visibility text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_result jsonb;
  v_profile_id uuid;
  v_anonymous_at_publish boolean;
  v_is_retry boolean;
begin
  if (select auth.uid()) is null then
    raise exception using errcode = '28000', message = 'AUTH_REQUIRED';
  end if;

  v_result := private.publish_announcement_core_v2(
    p_submission_id,
    p_payload,
    p_terms_version,
    p_privacy_version,
    p_visibility
  );

  if v_result ->> 'status' <> 'success' then
    return v_result;
  end if;

  v_is_retry := coalesce((v_result ->> 'idempotent')::boolean, false);
  if v_is_retry or p_payload ->> 'profile_type' <> 'giocatore' then
    return v_result;
  end if;

  select announcement.autore_annuncio, submission.anonymous_at_publish
  into v_profile_id, v_anonymous_at_publish
  from private.announcement_submission as submission
  join public.annuncio as announcement
    on announcement.uuid = submission.announcement_id
  where submission.submission_id = p_submission_id;

  if v_anonymous_at_publish then
    perform private.save_player_highlights_for_profile_v1(
      v_profile_id,
      'giocatore',
      p_payload -> 'profile_draft'
    );
  end if;

  return v_result;
end;
$$;

revoke all on function public.publish_announcement_v2(uuid, jsonb, text, text, text)
  from public, anon, authenticated, service_role;
grant execute on function public.publish_announcement_v2(uuid, jsonb, text, text, text)
  to authenticated;

create or replace function private.validate_profile_birth_date_v1()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_year_text text := nullif(pg_catalog.btrim(new.anno_nascita), '');
  v_month_text text := nullif(pg_catalog.btrim(new.mese_nascita), '');
  v_day_text text := nullif(pg_catalog.btrim(new.giorno_nascita), '');
  v_year integer;
  v_month integer;
  v_day integer;
  v_max_day integer;
  v_cutoff date := ((pg_catalog.statement_timestamp() at time zone 'Europe/Rome')::date - interval '14 years')::date;
begin
  if v_year_text is null and v_month_text is null and v_day_text is null then
    return new;
  end if;

  if v_year_text is null or v_year_text !~ '^[0-9]{4}$' then
    raise exception using errcode = '22023', message = 'INVALID_BIRTH_DATE';
  end if;
  v_year := v_year_text::integer;
  if v_year < 1900 then
    raise exception using errcode = '22023', message = 'INVALID_BIRTH_DATE';
  end if;

  v_month := case v_month_text
    when 'Gennaio' then 1
    when 'Febbraio' then 2
    when 'Marzo' then 3
    when 'Aprile' then 4
    when 'Maggio' then 5
    when 'Giugno' then 6
    when 'Luglio' then 7
    when 'Agosto' then 8
    when 'Settembre' then 9
    when 'Ottobre' then 10
    when 'Novembre' then 11
    when 'Dicembre' then 12
    else null
  end;

  if v_month_text is not null and v_month is null then
    raise exception using errcode = '22023', message = 'INVALID_BIRTH_DATE';
  end if;
  if v_day_text is not null and (
    v_month is null
    or v_day_text !~ '^[0-9]{1,2}$'
  ) then
    raise exception using errcode = '22023', message = 'INVALID_BIRTH_DATE';
  end if;

  if v_day_text is not null then
    v_day := v_day_text::integer;
    v_max_day := extract(day from (
      pg_catalog.make_date(v_year, v_month, 1)
      + interval '1 month'
      - interval '1 day'
    ))::integer;
    if v_day < 1 or v_day > v_max_day then
      raise exception using errcode = '22023', message = 'INVALID_BIRTH_DATE';
    end if;
  end if;

  if v_year > extract(year from v_cutoff)::integer then
    raise exception using errcode = '22023', message = 'MINIMUM_AGE_REQUIRED';
  end if;

  if v_year = extract(year from v_cutoff)::integer then
    if v_month is null
      or v_month > extract(month from v_cutoff)::integer
      or (
        v_month = extract(month from v_cutoff)::integer
        and (v_day is null or v_day > extract(day from v_cutoff)::integer)
      ) then
      raise exception using errcode = '22023', message = 'MINIMUM_AGE_REQUIRED';
    end if;
  end if;

  return new;
end;
$$;

revoke all on function private.validate_profile_birth_date_v1()
  from public, anon, authenticated, service_role;

drop trigger if exists validate_profile_birth_date_v1 on public.profilo_giocatore;
create trigger validate_profile_birth_date_v1
before insert or update of anno_nascita, mese_nascita, giorno_nascita
on public.profilo_giocatore
for each row execute function private.validate_profile_birth_date_v1();

drop trigger if exists validate_profile_birth_date_v1 on public.profilo_staff_sportivo;
create trigger validate_profile_birth_date_v1
before insert or update of anno_nascita, mese_nascita, giorno_nascita
on public.profilo_staff_sportivo
for each row execute function private.validate_profile_birth_date_v1();

drop trigger if exists validate_profile_birth_date_v1 on public.profilo_arbitro;
create trigger validate_profile_birth_date_v1
before insert or update of anno_nascita, mese_nascita, giorno_nascita
on public.profilo_arbitro
for each row execute function private.validate_profile_birth_date_v1();

drop trigger if exists validate_profile_birth_date_v1 on public.profilo_professionista_studente;
create trigger validate_profile_birth_date_v1
before insert or update of anno_nascita, mese_nascita, giorno_nascita
on public.profilo_professionista_studente
for each row execute function private.validate_profile_birth_date_v1();

create or replace function private.delete_player_highlights_v1()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  delete from public.media_profilo
  where uuid_profilo = old.uuid_profilo
    and formato_media = 'video_highlights';
  return old;
end;
$$;

revoke all on function private.delete_player_highlights_v1()
  from public, anon, authenticated, service_role;

drop trigger if exists delete_player_highlights_v1 on public.profilo_giocatore;
create trigger delete_player_highlights_v1
after delete on public.profilo_giocatore
for each row execute function private.delete_player_highlights_v1();
