-- Restore the player highlights sidecar helpers for deployments where the
-- profile save wrappers were installed without their supporting functions.

create table if not exists public.media_profilo (
  id bigint generated by default as identity primary key,
  uuid_profilo uuid not null references public.profilo (uuid) on delete cascade,
  formato_media text,
  link_media text not null
);

create index if not exists media_profilo_uuid_profilo_idx
  on public.media_profilo (uuid_profilo);

create unique index if not exists media_profilo_video_highlights_uidx
  on public.media_profilo (uuid_profilo)
  where formato_media = 'video_highlights';

alter table public.media_profilo enable row level security;
revoke all on table public.media_profilo from public, anon, authenticated;
grant select on table public.media_profilo to authenticated;
grant all on table public.media_profilo to service_role;

do $$
declare
  v_sequence text := pg_catalog.pg_get_serial_sequence('public.media_profilo', 'id');
begin
  if v_sequence is not null then
    execute pg_catalog.format(
      'grant usage, select on sequence %s to service_role',
      v_sequence
    );
  end if;
end;
$$;

drop policy if exists media_profilo_select_own on public.media_profilo;
create policy media_profilo_select_own
  on public.media_profilo
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.profilo as owned_profile
      join public.utente as owned_user
        on owned_user.utente_uuid = owned_profile.uuid_utente
      where owned_profile.uuid = media_profilo.uuid_profilo
        and owned_user.auth_user_uuid = (select auth.uid())
    )
  );

create or replace function private.save_player_highlights_for_profile_v1(
  p_profile_id uuid,
  p_profile_type text,
  p_draft jsonb
)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_link text;
begin
  if p_profile_type <> 'giocatore' then
    return;
  end if;

  if p_profile_id is null
    or p_draft is null
    or pg_catalog.jsonb_typeof(p_draft) <> 'object' then
    raise exception using errcode = '22023', message = 'INVALID_PROFILE_PAYLOAD';
  end if;

  if not p_draft ? 'video_highlights' then
    return;
  end if;

  if not exists (
    select 1
    from public.profilo_giocatore
    where uuid_profilo = p_profile_id
  ) then
    raise exception using errcode = 'P0001', message = 'PROFILE_NOT_FOUND';
  end if;

  v_link := nullif(pg_catalog.btrim(p_draft ->> 'video_highlights'), '');
  if v_link is not null and (
    pg_catalog.char_length(v_link) > 2048
    or v_link !~* '^https?://[^[:space:]]+$'
  ) then
    raise exception using errcode = '22023', message = 'INVALID_PROFILE_VIDEO_LINK';
  end if;

  if v_link is null then
    delete from public.media_profilo
    where uuid_profilo = p_profile_id
      and formato_media = 'video_highlights';
    return;
  end if;

  insert into public.media_profilo (
    uuid_profilo,
    formato_media,
    link_media
  ) values (
    p_profile_id,
    'video_highlights',
    v_link
  )
  on conflict (uuid_profilo)
    where formato_media = 'video_highlights'
  do update set link_media = excluded.link_media;
end;
$$;

revoke all on function private.save_player_highlights_for_profile_v1(uuid, text, jsonb)
  from public, anon, authenticated, service_role;
grant execute on function private.save_player_highlights_for_profile_v1(uuid, text, jsonb)
  to service_role;

create or replace function private.save_player_highlights_request_for_profile_v1(
  p_profile_id uuid,
  p_profile_type text,
  p_requested boolean
)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if p_profile_type <> 'giocatore' then
    if coalesce(p_requested, false) then
      raise exception using errcode = '22023', message = 'INVALID_PROFILE_PAYLOAD';
    end if;
    return;
  end if;

  if p_profile_id is null then
    raise exception using errcode = '22023', message = 'INVALID_PROFILE_PAYLOAD';
  end if;

  update public.profilo_giocatore
  set richiede_caricamento_highlights = coalesce(p_requested, false)
  where uuid_profilo = p_profile_id;
  if not found then
    raise exception using errcode = 'P0001', message = 'PROFILE_NOT_FOUND';
  end if;

  if coalesce(p_requested, false) then
    delete from public.media_profilo
    where uuid_profilo = p_profile_id
      and formato_media = 'video_highlights';
  end if;
end;
$$;

revoke all on function private.save_player_highlights_request_for_profile_v1(uuid, text, boolean)
  from public, anon, authenticated, service_role;
grant execute on function private.save_player_highlights_request_for_profile_v1(uuid, text, boolean)
  to service_role;
